version: "3.9"

services:
  db:
    image: postgres:16
    container_name: productprediction-db
    restart: always
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: appsecret
      POSTGRES_DB: productprediction
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d productprediction"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  api:
    build:
      context: ./API
      dockerfile: ProductPrediction.API/Dockerfile
    container_name: productprediction-api
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__Default: "Host=db;Port=5432;Database=productprediction;Username=appuser;Password=appsecret"
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend            # ajuste se o nome da pasta for outro
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "http://localhost:8080"   # URL interna da API (nome do servi√ßo)
    container_name: productprediction-front
    restart: always
    depends_on:
      api:
        condition: service_started
    ports:
      - "5173:80"                    # acessa em http://localhost:5173

volumes:
  postgres_data:
